### ISSUE TITLE
Add Foursquare datasets

### ISSUE THREAD

**Issue by lucaspetry** [trajminer/trajminer#50]
Add Foursquare NYC and Tokyo datasets from https://sites.google.com/site/yangdingqi/home/foursquare-dataset.

**Comment by falcaopetri** [comment]
I'm interested in using the Foursquare datasets in my master's project, especially a semantically enriched version, similar to the one used in the paper _"Towards semantic‐aware multiple‐aspect trajectory similarity measuring"_.

Would really like to see these datasets and the semantic-enrichment related functions added.

I suppose some preprocessing would be required to format the data similar to the ones in https://github.com/trajminer/data/. Then just adding the loading code to [datasets/base.py](https://github.com/trajminer/trajminer/blob/master/trajminer/datasets/base.py), and pushing the data to https://github.com/trajminer/data/.

Is that right? Let me know how to help!
