### ISSUE TITLE
Question about the repository

### ISSUE THREAD

**Issue by arthurpaulino** [trajminer/trajminer#59]
This repository looks cool :)

I'd love to participate and help, but it's kind of hard to understand what it's really about. Is it a collection of functions? A set of interconnected classes with a major purpose? How can your code help people, exactly?

Best regards.

**Comment by lucaspetry** [comment]
Thanks! I started this repo trying to put together tools/functions related to spatial data mining (trajectory data mining).
As I'm currently a master's student, this mostly reflects scientific works that my colleagues and I have been studying in our research or that somehow supports experiments I did.
Although it's a bit raw and very "academically driven", I think it would be cool if we could shape it and implement methods for real-world problems (I'm not sure if there is an open-source lib for that purpose).
What do you think?

**Comment by arthurpaulino** [comment]
I think it's an interesting idea.

I didn't think it was an academic project because I rarely see academic projects with meticulous coding practices, such as PEP8/Codacy and on-the-fly continuous integration tests.

The long-term shape of the repository, of course, would heavily depend on the initial, current and future needs of your team. But we can see what time will tell.

By the way, have you checked [GeoPy](https://geopy.readthedocs.io) yet?

**Comment by lucaspetry** [comment]
Well, let's say I started it after having trouble finding (or even coding) other people's code and making it work with my data, so it's also sort of "a favor" for future students haha.
I've set up the tests and code style checks because I did think it's important to start caring about that stuff from the beginning, but we actually don't have any tests yet.

I'm not sure I knew about GeoPy, but it looks like it's mainly about geocoding.

**Comment by arthurpaulino** [comment]
I see. I mentioned GeoPy because it implements a *Geodesic* distance and I didn't know what it was. But I did a [quick research](https://www.quora.com/What-is-geodesic-distance) and it seems to be the same as the Haversine distance, already implemented here.

Thank you for all the answers! By the way, I think a good way of showing what the project is about would be creating a few straightforward examples to display what kind of problems the lib can help solve. Of course, this takes time and your team has its own priorities.

**Comment by falcaopetri** [comment]
Hi, @lucaspetry! I'm also a master's student and I will be dealing with semantic trajectories in my project. I found this library through the paper _"Towards semantic‐aware multiple‐aspect trajectory similarity measuring"_, and considered your initiative really interesting!

I will use an ontology-based representation and explore some data mining tasks in my project. Now I am thinking about using Trajminer to do data manipulation, and as an abstraction layer of my project.

I was going to open an issue presenting myself, but then found this old topic. Let me know the best way to share my project's requirements and to contribute to this lib. May I just open a bunch of issues?
